name: ftauth_static
publish_to: none

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  codemirror: ^0.5.0
  http: ^0.12.0
  email_validator: ^1.0.6
  pool: ^1.4.0
  firebase: any

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  sass_builder: ^2.0.0

  grinder: ^0.8.6
  glob: ^1.2.0

  shelf: ^0.7.5
  shelf_static: ^0.2.8