name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  server:
    name: Server
    strategy:
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: golang:${{ matrix.go-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make server
