name: Docker (Latest)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  docker-latest:
    name: Docker (Latest)
    strategy:
      matrix:
        go-version: [1.15]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          tags: ftauth/ftauth:latest
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}