name: Server

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: golang:${{ matrix.go-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make server
  test:
    name: Test
    needs: build
    strategy:
      matrix:
        dgraph-version: [v20.11.2]
        go-version: [1.16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: golang:${{ matrix.go-version }}
    services:
      dgraph:
        image: dgraph/standalone:${{ matrix.dgraph-version }}
        ports:
        - 9080:9080
        - 8080:8080
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make server-test
        env:
          FTAUTH_DATABASE_URL: http://dgraph:8080/graphql
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: true
  deploy:
    name: Docker (Latest)
    needs: [build, test]
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        go-version: [1.16]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Inspect Builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Build and Push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          tags: ftauth/ftauth:latest
          push: true
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}
