name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  server:
    name: Server
    strategy:
      matrix:
        dgraph-version: [v21.03.2]
        go-version: [1.17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: dev
    container:
      image: golang:${{ matrix.go-version }}
    services:
      dgraph:
        image: dgraph/standalone:${{ matrix.dgraph-version }}
        ports:
        - 9080:9080
        - 8080:8080
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make server-test
        env:
          DGRAPH_URL: http://dgraph:8080/graphql
          DGRAPH_GRPC: http://dgraph:9080
          DGRAPH_SLASH_URL: ${{ secrets.DGRAPH_SLASH_URL }}
          DGRAPH_SLASH_GRPC: ${{ secrets.DGRAPH_SLASH_GRPC }}
          DGRAPH_SLASH_API_KEY: ${{ secrets.DGRAPH_SLASH_API_KEY }}
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: true
