name: Run Tests

# Run this everytime a new commit is pushed to the repo
on: push

jobs:
  go-test:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - run: go build ./...
      - run: go test -v -coverprofile=coverage.txt ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: true

  # flutter-test:
  #   name: Test frontend
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
      
  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v1
  #       with:
  #         channel: beta

  #     - run: bash scripts/ci.sh
  #       working-directory: web/admin
