name: Run Tests

# Run this everytime a new commit is pushed to the repo
on: push

jobs:
  go-test:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add Go to PATH
        uses: actions/setup-go@v2

      - run: go build ./...
      - run: go test -v ./...
