name: web
description: FTAuth script
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  js: ^0.6.3

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
